version: "3.9"
services:
  node:
    restart: "unless-stopped"
    stop_grace_period: 3m
    image: chainfliplabs/chainflip-node:${NODE_TAG}
    volumes:
      - node-data:/etc/chainflip
      - ./keys:/etc/chainflip/keys
      - ./config:/etc/chainflip/config
      - /etc/localtime:/etc/localtime:ro
    ports:
      - ${NODE_P2P_PORT:-30333}:${NODE_P2P_PORT:-30333}/tcp
    entrypoint:
      - /usr/local/bin/chainflip-node
      - --chain
      - /etc/chainflip/perseverance.chainspec.json
      - --base-path
      - /etc/chainflip/chaindata
      - --node-key-file
      - /etc/chainflip/keys/node_key_file
      - --validator
      - --prometheus-external
      - --port
      - ${NODE_P2P_PORT:-30333}
      - --unsafe-rpc-external
      - --rpc-cors=*
      - --rpc-methods
      - unsafe
      - --log
      - ${LOG_LEVEL}
      - --database
      - paritydb
      - --sync
      - ${SYNC_MODE}
      - --execution
      - native

  engine:
    restart: "unless-stopped"
    image: chainfliplabs/chainflip-engine:${ENGINE_TAG}
    ulimits:
      nofile:
        soft: 16000
        hard: 16000
    environment:
      - RUST_LOG=${LOG_LEVEL}
    volumes:
      - engine-data:/etc/chainflip
      - ./keys:/etc/chainflip/keys
      - ./config:/etc/chainflip/config
      - /etc/localtime:/etc/localtime:ro
    ports:
      - ${ENGINE_P2P_PORT:-8078}:${ENGINE_P2P_PORT:-8078}/tcp
    entrypoint:
      - /usr/local/bin/chainflip-engine
      - --config-root
      - /etc/chainflip

  cli:
    restart: "no"
    profiles: ["tools"]
    image: chainfliplabs/chainflip-cli:${CLI_TAG}
    volumes:
      - ./keys:/etc/chainflip/keys
      - ./config:/etc/chainflip/config
      - /etc/localtime:/etc/localtime:ro
    entrypoint:
      - /usr/local/bin/chainflip-cli
      - --config-root
      - /etc/chainflip

volumes:
  node-data:
  engine-data:
