version: "3.9"
services:
  old-engine:
    restart: "unless-stopped"
    image: chainfliplabs/chainflip-engine:${OLD_ENGINE_TAG}
    ulimits:
      nofile:
        soft: 16000
        hard: 16000
    environment:
      - RUST_LOG=${LOG_LEVEL}
    volumes:
      - engine-data:/etc/chainflip
      - ./keys:/etc/chainflip/keys
      - /etc/localtime:/etc/localtime:ro
    ports:
      - ${OLD_ENGINE_P2P_PORT:-8079}:${OLD_ENGINE_P2P_PORT:-8079}/tcp
    entrypoint:
      - /usr/local/bin/chainflip-engine
      - --btc.rpc.http_endpoint
      - ${BTC_RPC}
      - --btc.rpc.basic_auth_user
      - ${BTC_USER}
      - --btc.rpc.basic_auth_password
      - ${BTC_PASSWORD}
      - --btc.backup_rpc.http_endpoint
      - ${BTC_BACKUP_RPC}
      - --btc.backup_rpc.basic_auth_user
      - ${BTC_BACKUP_USER}
      - --btc.backup_rpc.basic_auth_password
      - ${BTC_BACKUP_PASSWORD}
      - --dot.rpc.http_endpoint
      - ${DOT_RPC}
      - --dot.rpc.ws_endpoint
      - ${DOT_WS}
      - --dot.backup_rpc.http_endpoint
      - ${DOT_BACKUP_RPC}
      - --dot.backup_rpc.ws_endpoint
      - ${DOT_BACKUP_WS}
      - --eth.rpc.http_endpoint
      - ${ETH_RPC}
      - --eth.rpc.ws_endpoint
      - ${ETH_WS}
      - --eth.backup_rpc.http_endpoint
      - ${ETH_BACKUP_RPC}
      - --eth.backup_rpc.ws_endpoint
      - ${ETH_BACKUP_WS}
      - --eth.private_key_file
      - /etc/chainflip/keys/ethereum_key_file
      - --health_check.hostname
      - 0.0.0.0
      - --health_check.port
      - "5555"
      - --p2p.ip_address
      - ${HOST_IP}
      - --p2p.port
      - ${OLD_ENGINE_P2P_PORT:-8079}
      - --p2p.node_key_file
      - /etc/chainflip/keys/node_key_file
      - --signing.db_file
      - /etc/chainflip/data.db
      - --state_chain.signing_key_file
      - /etc/chainflip/keys/signing_key_file
      - --state_chain.ws_endpoint
      - ws://node:9944
      - --prometheus.hostname
      - 0.0.0.0
      - --prometheus.port
      - "5566"
    labels:
      - metrics.scrape=true
      - metrics.path=/metrics
      - metrics.port=5566

volumes:
  engine-data:
